services:
  gluetun_open:
    image: qmcgaw/gluetun
    container_name: gluetun_open
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    ports:
    - 8888:8888/tcp # HTTP proxy
    - 8388:8388/tcp # Shadowsocks
    - 8388:8388/udp # Shadowsocks
    - 8180:8180 # port for qbittorrent
    - 6881:6881 # torrent port for qbittorrent
    - 6881:6881/udp # torrent port for qbittorrent
    - 16969:16969 # port for qbittorrent_whisparr
    - 6882:6882 # torrent port for qbittorrent_whisparr
    - 6882:6882/udp # torrent port for qbittorrent_whisparr
    - 6789:6789 # nzbget
    - 3033:3033 #yt-dlp
    - 3034:8081 #metube
    - 5800:5800 #jdownloader
    - 3129:3129 #myjdownloader
    # - 6969:6969 #whisparr
    # - 7878:7878 # radaar
    # - 8989:8989 #sonarr
    # - 6767:6767 #bazaar
    # - 8280:8280 # port for sabnzb
    volumes:
    - $DOCKERCONFIGS_DIR/gluetun/config:/gluetun    
    environment:
    - VPN_SERVICE_PROVIDER=$VPNPROVIDER
    - OPENVPN_USER=$VPNUSERID
    - OPENVPN_PASSWORD=$VPNPASSWORD
    - SERVER_REGIONS=$VPNREGION # Replace with your preferred region
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s      
    restart: unless-stopped
    networks:
      - arr-network

  qbittorrent_client:
      image: lscr.io/linuxserver/qbittorrent
      container_name: qbittorrent_client
      depends_on:
      - gluetun_open 
      network_mode: service:gluetun_open
      environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=$TZ
        - WEBUI_PORT=8180
        - TORRENTING_PORT=6881
      volumes:
        - $LOCALDOCKER_DIR/qbittorrent/config:/config
        #- $DATA_DIR/downloads/torrents:/downloads
        - $DATA_DIR/downloads/torrents:/$DATA_DIR/downloads/torrents
      restart: unless-stopped # no | always | on-failure | unless-stopped
     
  # nzbget:
  #   image: lscr.io/linuxserver/nzbget:latest
  #   container_name: nzbget
  #   depends_on:
  #     - gluetun_open 
  #   network_mode: service:gluetun_open 
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     - NZBGET_USER=nzbget #optional
  #     - NZBGET_PASS=123abc #optional
  #   volumes:
  #     - $LOCALDOCKER_DIR/nzbget/config:/config
  #     - $DATA_DIR/downloads/usenet:$DATA_DIR/downloads/usenet #optional
  #   restart: unless-stopped

  # sabnzb:
  #   image: lscr.io/linuxserver/sabnzbd
  #   container_name: sabnzb
  #   #hostname: nzbget #produces an error against network-mode
   
  #   ports:
  #     - 8280:8280
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #   volumes:
  #     - $LOCALDOCKER_DIR/sabnzb/config:/config
  #     - $DATA_DIR/downloads/usenet/:/$DATA_DIR/downloads/usenet #optional
  #     - $DATA_DIR/downloads/usenet/intermediate:/incomplete-downloads #optional
  #   restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    # depends_on:
    #   - gluetun_open 
    # network_mode: service:gluetun_open
    ports:
      - 7878:7878 # radaar
    
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LOCALDOCKER_DIR/radarr/config:/config
      - $DATA_DIR:/data    
      - $DOCKERCONFIGS_DIR/radarr/custom-services.d:/custom-services.d  
      - $DOCKERCONFIGS_DIR/radarr/custom-cont-init.d:/custom-cont-init.d
    restart: unless-stopped
    networks:
      - arr-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # depends_on:
    #   - gluetun_open 
    # network_mode: service:gluetun_open
    ports:
      - 8989:8989 #sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LOCALDOCKER_DIR/sonarr/config:/config
      - $DATA_DIR:/data  
    restart: unless-stopped
    networks:
      - arr-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    # depends_on:
    #   - gluetun_open 
    # network_mode: service:gluetun_open
    ports:
      - 6767:6767
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LOCALDOCKER_DIR/bazarr/config:/config
      - $DATA_DIR/media/movies:/movies #optional
      - $DATA_DIR/media/tv:/tv #optional
    restart: unless-stopped
    networks:
      - arr-network

  qbittorrent_whisparr:
      image: lscr.io/linuxserver/qbittorrent
      container_name: qbittorrent_whisparr
      depends_on:
      - gluetun_open 
      network_mode: service:gluetun_open
      environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=$TZ
        - WEBUI_PORT=16969
        - TORRENTING_PORT=6882
      volumes:
        - $LOCALDOCKER_DIR/qbittorrent_whisparr/config:/config
        #- $DATA_DIR/downloads/torrents:/downloads
        - $DATA_DIR/privatestuff/downloads/torrents:/$DATA_DIR/privatestuff/downloads/torrents
      restart: unless-stopped # no | always | on-failure | unless-stopped


  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    #depends_on:
    #   - gluetun_open 
    #network_mode: service:gluetun_open
    ports:
      - 6969:6969
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - $LOCALDOCKER_DIR/whisparr/config:/config
      - $DATA_DIR/privatestuff:/$DATA_DIR/privatestuff
    restart: unless-stopped
    networks:
      - arr-network

  whisparr3:
    container_name: whisparr3
    image: ghcr.io/hotio/whisparr:v3
    #depends_on:
    #   - gluetun_open 
    #network_mode: service:gluetun_open
    ports:
      - 36969:6969
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - $LOCALDOCKER_DIR/whisparr3/config:/config
      - $DATA_DIR/privatestuff:/$DATA_DIR/privatestuff
    restart: unless-stopped
    networks:
      - arr-network

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    # depends_on:
    #   - gluetun_open 
    # network_mode: service:gluetun_open
    ports:
      - "9696:9696"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - $LOCALDOCKER_DIR/prowlarr/config:/config
    restart: unless-stopped
    networks:
      - arr-network

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    # depends_on:
    #   - gluetun_open 
    # network_mode: service:gluetun_open
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}      
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - arr-network

  jellyseerr:
    image: seerr/seerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - $LOCALDOCKER_DIR/jellyseerr/config:/app/config
    #healthcheck:
      #test: wget --no-verbose --tries=1 --spider http://192.168.68.86:5055/api/v1/status || exit 1
      #start_period: 20s
      #timeout: 3s
      #interval: 15s
      #retries: 3
    restart: unless-stopped
    networks:
      - arr-network


  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui  
    container_name: yt-dlp-webui
    depends_on:
      - gluetun_open 
    network_mode: service:gluetun_open
    volumes:
      - $DATA_DIR/media/youtube:/downloads # replace <your dir> with a directory on your host system
      - $DATA_DIR/media/otherstuff/yt-dlp:/otherstuff
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped

  # subscribarr:
  #   image: 10010011/subscribarr:latest
  #   container_name: subscribarr
  #   ports:
  #     - "8181:8000"
  #   environment:
  #     - DJANGO_ALLOWED_HOSTS=*
  #     - DJANGO_SECRET_KEY=change-me
  #     - NOTIFICATIONS_ALLOW_DUPLICATES=false
  #     - DJANGO_CSRF_TRUSTED_ORIGINS="http://localhost:8181,http://127.0.0.1:8181"
  #     # Cron schedule (default every 30min)
  #     - CRON_SCHEDULE=*/30 * * * *
  #   volumes:
  #     - $DATA_DIR/media/subscribarr:$DATA_DIR/media/subscribarr
  #     - $DATA_DIR/media:$DATA_DIR/allmedia      
  #   restart: unless-stopped

  # metube:
  #   image: ghcr.io/alexta69/metube
  #   container_name: metube
  #   depends_on:
  #     - gluetun_open 
  #   network_mode: service:gluetun_open
  #   restart: unless-stopped
  #   volumes:
  #     - $DATA_DIR/media/youtube:$DATA_DIR/media/youtube # replace <your dir> with a directory on your host system
   
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    depends_on:
      - gluetun_open 
    network_mode: service:gluetun_open
    # ports:
    #   - 5800:5800
    environment:     
      - USER_ID=$PUID
      - GROUP_ID=$PGID
      - TZ=$TZ
      - MYJDOWNLOADER_EMAIL=$JDOWNLOADEMAIL
      - MYJDOWNLOADER_PASSWORD=$JDOWNLOADPASS
      - MYJDOWNLOADER_DEVICE_NAME=arrserver
      - JDOWNLOADER_HEADLESS=1
    volumes:
      - $LOCALDOCKER_DIR/jdownloader:/config
      - $DATA_DIR/downloads/jdownloader:/output
    restart: unless-stopped

  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LOCALDOCKER_DIR/trailarr:/config # For Trailarr's database and logs
      # Map your Radarr media folder(s)
      - $DATA_DIR/media/movies:/media/movies # Example: if Radarr uses /media/movies internally
      # Map your Sonarr media folder(s)
      - $DATA_DIR/media/tv:/media/tv # Example: if Sonarr uses /media/tv internally
      # Add more volume mappings if you have multiple Radarr/Sonarr instances
      # or if your media is split across different locations.
      # The path on the right (e.g., /media/movies, /media/tv) is how Trailarr will see these folders.
      # The path on the left is the actual path on your Docker host system.
    ports:
      - 7889:7889 # Or choose a different host port if 7889 is taken, leave the right side as is
    restart: unless-stopped
    networks:
      - arr-network

    # 1. Define the shared custom network here
networks:
  arr-network:
    driver: bridge
