# host_vars/vm3-internal.yml
kopia_client_password: "{{ vault_kopia_client_pw_vm3_internal }}"

kopia_backup_paths:
  - path: "{{ LOCALDOCKER_DIR }}"
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 3
